from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import config
import time

driver = webdriver.Chrome("../chromedriver.exe")

# driver.add_cookie({"name": "messenger.com", "value": "WWdGY4wZuqNx-uigp68IN6wb"})
# driver.add_cookie({"domain": ".messenger.com", "expiry'": 1700118373, "httpOnly": True, "name": "datr", "path": "/", "sameSite": None, "secure": True, "value": "WWdGY4wZuqNx-uigp68IN6wb"})


driver.get("https://www.messenger.com/t/2022213241239792")

print("Current email is '" + config.email + "' Current password is '" + config.password + "'")

time.sleep(7)

print("Login in...")
driver.find_element(By.NAME, "email").send_keys(config.email)
driver.find_element(By.NAME, "pass").send_keys(config.password + Keys.RETURN)

time.sleep(5)

#print(driver.find_element(By.ID, "jsc_c_3p"))
driver.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/div/div/div/div[1]/div[1]/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[4]/div[2]/div/div/div[1]/p").send_keys(
   "Halal a feketerkre (Content generated by adri.py)" + Keys.RETURN)

time.sleep(10)

driver.quit()
